////
SPDX-FileCopyrightText: © 2012 Germar Reitze
SPDX-FileCopyrightText: © 2013 Oprea Dan
SPDX-FileCopyrightText: © 2022 Jürgen Altfeld (aryoda)
SPDX-FileCopyrightText: © 2023 Christian Buhtz <c.buhtz@posteo.jp>

SPDX-License-Identifier: GPL-2.0-or-later

This file is part of the program "Back In Time" which is released under GNU
General Public License v2 (GPLv2). See LICENSES directory or go to
<https://spdx.org/licenses/GPL-2.0-or-later.html>.
////
= backintime-qt(1)
:doctype: manpage
:manmanual: Back In Time
:mansource: backintime-qt {version}
:man-linkstyle: pass:[blue R < >]

== NAME

backintime-qt - Graphical Frontend for Back In Time

== SYNOPSIS

*backintime-qt*
[--help | -h]
[--version]
[--license]
[--debug]
<command>
[<args>]

== DESCRIPTION

A graphical frontend (GUI) for *Back In Time*, offering a user-friendly and
configurable interface for managing incremental backups. Modified files are
copied, while unchanged files are efficiently linked using the hard link
feature of *rsync*(1) to minimize storage usage.

Backups can be restored easily via the file manager, the command line, or
directly within the *Back In Time* interface.

For detailed information, see *backintime* (1). Command-line options and
arguments provided to *backintime-qt*(1) are passed directly to
*backintime*(1).

To run the application with root privileges, use *backintime-qt_polkit*.

== OPTIONS

*-h*, *--help*::  Display a short help.

*-v*, *--version*:: Show version.

*--license*:: Show license.

*--debug*::   Show debug messages.

See *backintime*(1) for more options.

== COMMANDS

See *backintime*(1) for commands.


== SEE ALSO

*backintime*(1), *backintime-config*(1), *backintime-askpass*(1)

*Back In Time* project website: https://github.com/bit-team/backintime

*Back In Time* mailing list: https://mail.python.org/mailman3/lists/bit-dev.python.org

== AUTHOR

*Back In Time* Team
